version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    user: "501:20"
    ports:
      - "3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  phpfpm:
    image: 10up/phpfpm:7.1
    user: "33:33"
    depends_on:
      - mysql
    volumes_from:
      - volumes_container
    networks:
      - backend
      - mail
    volumes:
      - "./wordpress:/var/www/html:delegated"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./config/php-fpm/docker-php-ext-xdebug-7.1.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro"
    restart: always
    external_links:
      - proxy_mailhog_1:mailcatcher
      - wpjmcom_nginx_1:wpjm-com
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80"
      - "443"
    networks:
      - frontend
      - backend
    image: nginx:latest
    volumes_from:
      - volumes_container
    volumes:
      - "./wordpress:/var/www/html:ro"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./config/certs:/etc/nginx/certs:ro"
      - "./logs/nginx:/var/log/nginx"
    restart: always
  volumes_container:
    image: busybox
networks:
  frontend:
  backend:
  mail:
    external:
      name: mail